### ISSUE TITLE
Add support to collect unknown properties into a map like Jackson's @JsonAnySetter

### ISSUE THREAD

**Issue by thiagolocatelli** [beosign/snakeyaml-anno#24]
If I have a property in the yaml that has not been mapped to a POJO attribute, does your library support adding this property to a Map object? Something similar to @JsonAnySetter from Jackson .

Reference: `https://www.logicbig.com/tutorials/misc/jackson/jackson-any-setter.html`

I would be interested in using this library but I miss this requirement from it.

Thank you

**Comment by beosign** [comment]
Hi,
unfortunately, I don't see a way to fulfill your requirement right now with the current code base. But I really like the idea, so I will look into it and try to include the functionality into the next release. I have not that much free time, but until the weekend I think I will have at least some news.

Kind regards

**Comment by thiagolocatelli** [comment]
@beosign Thanks for looking into it. I appreciate your work.

**Comment by beosign** [comment]
@thiagolocatelli Do you also need the @JsonAnyGetter functionality?

**Comment by thiagolocatelli** [comment]
@beosign this feature could also be there so we have both ways for unmapped properties.

**Comment by beosign** [comment]
Hi, I have uploaded a pre-version that implements the @YamlAnySetter feature. You can try it out here: https://github.com/beosign/snakeyaml-anno/releases/tag/1.1.0-preview-1
Just implement a public method with two parameters; one of type `String`, the other of type `Object`, and annotate the method with `@YamlAnySetter`
I hope this fits your needs; if not, please contact me.

Kind regards

**Comment by thiagolocatelli** [comment]
It does work for what I need. Thank you very much @beosign
