### ISSUE TITLE
Property converter is never applied

### ISSUE THREAD

**Issue by stefan-s29** [beosign/snakeyaml-anno#32]
Hello,

Thanks a lot for the work put into this package. I hope it is okay for me to ask for help here.

I have added SnakeYAML-anno 1.2.0 as a dependency to my _LibGDX_ core project via _jitpack.io_. Unfortunately, I cannot even get a very simple example to run, the converter that I implemented for a property is simply never called.

My root class:
```
public class SimpleClass {

    @YamlProperty(converter = SimpleStringConverter.class)
    private String myStringProperty;

    public String getMyStringProperty() {
        return myStringProperty;
    }

    public void setMyStringProperty(String myStringProperty) {
        this.myStringProperty = myStringProperty;
    }
}
```

The converter class:
```
public class SimpleStringConverter implements Converter<String> {

    @Override
    public String convertToYaml(String modelValue) {
        return null; // TODO
    }

    @Override
    public String convertToModel(Object value) {
        System.out.println("Called the SimpleStringConverter! Value: " + value);
        return (String) value;
    }

}
```

The part where SnakeYAML is used:
```
try (InputStream inputStream = Gdx.files.internal(filename).read() ) {
      Yaml yaml = new Yaml(new AnnotationAwareConstructor(SimpleClass.class));
      SimpleClass obj = yaml.load(inputStream);
      System.out.println(obj);
      return obj;
  }  catch (IOException e) {
      System.out.println("An error occured while trying to parse YAML file '" + filename + "': " + e);
  }
```

The YAML file:
```
---
myStringProperty: Hello world!
```

The _System.out.println()_ in the _convertToModel()_ function is not called. I also confirmed in debug mode that this line of the code is never reached.

At first I thought that it might have to do with me calling stuff from a _JUnit_ test, but the result is the same if I call it in the main program.

Am I missing something? Your help would be highly appreciated.

**Comment by beosign** [comment]
Hi @schaetz,
I think the problem is that you tried to annotate a private field. Please try annotating the public getter or make the field public, then it should work.

**Comment by stefan-s29** [comment]
You are absolutely right. It seems I didn't read the Readme careful enough.

Thanks for the quick help!
